version: '2.0'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/.ssl:/etc/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx
      - ./www:/usr/share/nginx/html
